
name: Build & Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-scan:
    name: Build Docker Image and Run Trivy Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t demo-trivy-app .

      - name: Create reports directory
        run: mkdir -p trivy-reports

      - name: Trivy FS Scan (source code)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: .
          format: table
          severity: CRITICAL,HIGH
          output: trivy-reports/fs-report.txt

      - name: Trivy Image Scan (Docker image)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          scan-ref: demo-trivy-app
          format: table
          severity: CRITICAL,HIGH
          output: trivy-reports/image-report.txt

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: trivy-reports/
