name: SSDNodes Connectivity Test
on:
  workflow_dispatch:  # Run manually from Actions tab

jobs:
  test-connectivity:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key file
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
      
      - name: Test connection to SSDNodes server
        run: |
          # Test SSH connection
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} '
            echo "Successfully connected to server!"
            echo "Server hostname: $(hostname)"
            echo "Docker status: $(docker info --format "{{.ServerVersion}}" || echo "Docker not available")"
          '
      
      - name: Remove SSH key
        if: always()
        run: |
          rm -f /tmp/id_rsa
